# -*- coding: utf-8 -*-
"""problem1_aml_golub_oleksandra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPQzFJn6W6HqYxpg_ZM5YUiGFwpScxCt

## **Advanced Machine Learning (Assignment 2, Problem 1)**
---
---

Università degli Studi Milano Bicocca \
CdLM Informatica — A.A 2025/2026

---
---

#### **Componenti del gruppo:**
— Oleksandra Golub (856706)

---
---

Link al dataset che ho utilizzato: [Fashion MNIST dataset](https://keras.io/api/datasets/fashion_mnist/)

---
---
"""

from google.colab import drive
import os
import random
import shutil
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import fashion_mnist

os.environ["TF_DETERMINISTIC_OPS"]="1"
random.seed(42); np.random.seed(42); tf.random.set_seed(42)

# Monta Google Drive
drive.mount('/content/drive')

# Path della cartella
drive_folder = '/content/drive/MyDrive/Assignment 2 AML/problem 1'

# Verifica cartella
print(f"\nCartella: {drive_folder}")
print(f"Esiste? {os.path.exists(drive_folder)}")

if os.path.exists(drive_folder):
    print("\nFile disponibili:")
    for file in os.listdir(drive_folder):
        print(f"  - {file}")

    # Copia file con shutil (più affidabile)
    print("\nCopia file in corso...")
    files_to_copy = {
        'problem_one.weights.h5': 'problem_one.weights.h5',
        'Problem 1_accuracy.png': 'original_accuracy.png',
        'Problem 1_loss.png': 'original_loss.png',
        'problem_one (2).png': 'architecture.png'
    }

    for source_name, dest_name in files_to_copy.items():
        source = os.path.join(drive_folder, source_name)
        if os.path.exists(source):
            shutil.copy2(source, dest_name)
            print(f" {source_name} → {dest_name}")
        else:
            print(f" {source_name} non trovato")

# 1. CARICAMENTO DATASET
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

# 2. PREPROCESSING
# Normalizzazione pixel values [0, 255] → [0, 1]
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Flatten 28x28 → 784
x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

print(f"Training set: {x_train.shape} con labels: {y_train.shape}")
print(f"Test set: {x_test.shape} con labels: {y_test.shape}")

# Nomi delle classi Fashion-MNIST
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# 3. RICOSTRUZIONE DELL'ARCHITETTURA ORIGINALE
def create_model():
    """
    Architettura basata sull'immagine problem_one (2).png:
    Input (784) -> Dense(512) -> Dense(128) -> Dense(64) -> Dense(10)
    """
    model = keras.Sequential([
        layers.Dense(512, activation='relu', input_shape=(784,), name='layer-one'),
        layers.Dense(128, activation='relu', name='layer-two'),
        layers.Dense(64, activation='relu', name='layer-three'),
        layers.Dense(10, activation='softmax', name='layer-four')
    ])
    return model

model_architecture = create_model()
model_architecture.summary()

# 4. CARICAMENTO DEL MODELLO PROBLEMATICO CON I PESI FORNITI
model_problematic = create_model()

# Compilamento con gli stessi parametri usati per il training
model_problematic.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.1),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Caricamento dei pesi
try:
    model_problematic.load_weights('problem_one.weights.h5')
    print("Pesi caricati con successo!")
except Exception as e:
    print(f"Errore nel caricamento dei pesi: {e}")

# 5. VALUTAZIONE DEL MODELLO PROBLEMATICO
train_loss_prob, train_acc_prob = model_problematic.evaluate(
    x_train, y_train, verbose=0, batch_size=128
)
test_loss_prob, test_acc_prob = model_problematic.evaluate(
    x_test, y_test, verbose=0, batch_size=128
)

print(f"\n Risultati del modello problematico (lr=0.1):")
print(f"  Training Accuracy: {train_acc_prob:.4f} ({train_acc_prob*100:.2f}%)")
print(f"  Training Loss: {train_loss_prob:.4f}")
print(f"  Validation Accuracy:{test_acc_prob:.4f} ({test_acc_prob*100:.2f}%)")
print(f"  Validation Loss: {test_loss_prob:.4f}")

# Analisi predizioni
print("\n Analisi predizioni su 1000 samples:")
sample_size = 1000
predictions = model_problematic.predict(x_test[:sample_size], verbose=0)
predicted_classes = np.argmax(predictions, axis=1)
true_classes = y_test[:sample_size]

correct = np.sum(predicted_classes == true_classes)
print(f"  Accuracy: {correct}/{sample_size} = {correct/sample_size:.2%}")

# Distribuzione predizioni
print("\n Distribuzione delle predizioni:")
for i in range(10):
    count = np.sum(predicted_classes == i)
    print(f" Classe {i} ({class_names[i]:12s}): {count:3d} ({count/sample_size:5.1%})")

# Check se è vicino a random (10% per classe)
print(f"\n Random baseline accuracy: 10% (1 classe su 10)")
print(f" Performance attuale: {test_acc_prob*100:.1f}%")
if test_acc_prob < 0.3:
    print("\n Il modello performa quasi a livello random! (divergenza)")
elif test_acc_prob < 0.5:
    print("\n Il modello performa male (possibile divergenza parziale)")
else:
    print("\n Il modello apprende qualcosa, ma c'è spazio per miglioramenti")

# STEP 6: TRAINING MODELLO CORRETTO

model_fixed = create_model()
model_fixed.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_fixed = model_fixed.fit(
    x_train, y_train,
    batch_size=128,
    epochs=10,
    validation_data=(x_test, y_test),
    verbose=1
)

# STEP 7: CONFRONTO RISULTATI

train_acc_fixed = history_fixed.history['accuracy'][-1]
val_acc_fixed = history_fixed.history['val_accuracy'][-1]
train_loss_fixed = history_fixed.history['loss'][-1]
val_loss_fixed = history_fixed.history['val_loss'][-1]

print(" MODELLO PROBLEMATICO (lr=0.1, pesi forniti)")
print(f"  Training Accuracy:   {train_acc_prob:.4f} ({train_acc_prob*100:.2f}%)")
print(f"  Validation Accuracy: {test_acc_prob:.4f} ({test_acc_prob*100:.2f}%)")
print(f"  Training Loss:       {train_loss_prob:.4f}")
print(f"  Validation Loss:     {test_loss_prob:.4f}")

print("\n MODELLO CORRETTO (lr=0.001, trainato da zero)")
print(f"  Training Accuracy:   {train_acc_fixed:.4f} ({train_acc_fixed*100:.2f}%)")
print(f"  Validation Accuracy: {val_acc_fixed:.4f} ({val_acc_fixed*100:.2f}%)")
print(f"  Training Loss:       {train_loss_fixed:.4f}")
print(f"  Validation Loss:     {val_loss_fixed:.4f}")

print("\n MIGLIORAMENTO")
acc_improvement = val_acc_fixed - test_acc_prob
loss_improvement = test_loss_prob - val_loss_fixed
acc_percentage = (acc_improvement / test_acc_prob * 100) if test_acc_prob > 0 else 0

print(f"  Validation Accuracy: {acc_improvement:+.4f} ({acc_percentage:+.1f}%)")
print(f"  Validation Loss:     {loss_improvement:+.4f}")

if acc_improvement > 0.3:
    print("\n Il problema era chiaramente il learning rate!")
elif acc_improvement > 0.1:
    print("\n  Il learning rate era un problema significativo!")
else:
    print("\n  Miglioramento limitato. Potrebbero esserci altri problemi.")

# STEP 7: VISUALIZZAZIONE

fig = plt.figure(figsize=(18, 12))
gs = fig.add_gridspec(3, 2, hspace=0.3, wspace=0.3)

# riga dei grafici originali
ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[0, 1])

try:
    img_loss = plt.imread('Problem 1_loss.png')
    ax1.imshow(img_loss)
    ax1.axis('off')
    ax1.set_title('Original Problematic Model Loss (lr=0.1)', fontsize=12)
except:
    ax1.text(0.5, 0.5, 'Loss graph not found', ha='center', va='center', fontsize=12)
    ax1.axis('off')

try:
    img_acc = plt.imread('Problem 1_accuracy.png')
    ax2.imshow(img_acc)
    ax2.axis('off')
    ax2.set_title('Original Problematic Model Accuracy (lr=0.1)', fontsize=12)
except:
    ax2.text(0.5, 0.5, 'Accuracy graph not found', ha='center', va='center', fontsize=12)
    ax2.axis('off')

# riga dei grafici del modello corretto (loss)
ax3 = fig.add_subplot(gs[1, 0])
ax3.plot(history_fixed.history['loss'],
         label='Train Loss', linewidth=2.5, marker='o', markersize=6, color='blue')
ax3.plot(history_fixed.history['val_loss'],
         label='Validation Loss', linewidth=2.5, marker='s', markersize=6, color='orange')
ax3.set_title('Corretti Training e Validation Loss (lr=0.001)', fontsize=12)
ax3.set_xlabel('Epoch', fontsize=11)
ax3.set_ylabel('Loss', fontsize=11)
ax3.legend(fontsize=9)
ax3.grid(True, alpha=0.3)

# riga dei grafici del modello corretto (accuracy)
ax4 = fig.add_subplot(gs[1, 1])
ax4.plot(history_fixed.history['accuracy'],
         label='Train Accuracy', linewidth=2.5, marker='o', markersize=6, color='blue')
ax4.plot(history_fixed.history['val_accuracy'],
         label='Validation Accuracy', linewidth=2.5, marker='s', markersize=6, color='orange')
ax4.set_title('Corretti Training e Validation Accuracy (lr=0.001)', fontsize=12)
ax4.set_xlabel('Epoch', fontsize=11)
ax4.set_ylabel('Accuracy', fontsize=11)
ax4.legend(fontsize=9)
ax4.grid(True, alpha=0.3)

# confronto finale
ax5 = fig.add_subplot(gs[2, :])
categories = ['Training\nAccuracy', 'Validation\nAccuracy', 'Training\nLoss', 'Validation\nLoss']
problematic_values = [train_acc_prob, test_acc_prob, train_loss_prob, test_loss_prob]
fixed_values = [train_acc_fixed, val_acc_fixed, train_loss_fixed, val_loss_fixed]

x = np.arange(len(categories))
width = 0.35

bars1 = ax5.bar(x - width/2, problematic_values, width, label='Problematic (lr=0.1)',
                color='red', alpha=0.7)
bars2 = ax5.bar(x + width/2, fixed_values, width, label='Corrected (lr=0.001)',
                color='green', alpha=0.7)

ax5.set_ylabel('Value', fontsize=12)
ax5.set_title('Confronto tra modello problematico e corretto',
              fontsize=14, fontweight='bold')
ax5.set_xticks(x)
ax5.set_xticklabels(categories, fontsize=10)
ax5.legend(fontsize=11)
ax5.grid(True, alpha=0.3, axis='y')

# Aggiungi valori sopra le barre
for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        ax5.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.3f}',
                ha='center', va='bottom', fontsize=9)
plt.show()